baseURL = "
languageCode = "en-us"
title = ""
theme = "minimal"

pygmentsStyle = "native"
pygmentsOptions = "linenos=table"

[params]
	author = "Can Sürmeli"
	description = ""
	githubUsername = ""
	highlight = true
	highlightStyle = "solarized-dark"
	highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
	copyright= "Powered by [Hugo](https://gohugo.io)"

[params.matomo]
	url = ""

[params.staticman]
	endpoint = "https://api.staticman.net/v2/entry/"
	username = ""
	repository = ""
	branch = "master"

[[menu.main]]
	url = "/"
	name = "Home"
	weight = 1

[[menu.main]]
	url = "/about-me/"
	name = "About Me"
	weight = 2

[[menu.main]]
	url = "/posts/"
	name = "Posts"
	weight = 3

[[menu.main]]
	url = "/projects/"
	name = "Projects"
	weight = 4

[[menu.icon]]
	url = "mailto:"
	name = "far fa-envelope"
	weight = 1

[[menu.icon]]
	url = ""
	name = "fab fa-github"
	weight = 2

[[menu.icon]]
	url = ""
	name = "fab fa-twitter"
	weight = 3

[[menu.icon]]
	url = ""
	name = "fab fa-stack-overflow"
	weight = 4

[[menu.icon]]
	url = ""
	name = "fab fa-500px"
	weight = 5

